package day10;

public class C01_Record {

    /*
    As of JDK 14, we can replace our repetitious data classes with records.
    Records are immutable data classes that require only the type and name of fields.
    The equals, hashCode, and toString methods, as well as the private, final fields and public constructor, are generated by the Java compiler.
    We can also include static variables and methods in our records.
    Can not define our own instance variables
    We cannot extend the Record class.
    Record classes allow us to implement interfaces.
     */
    public static void main(String[] args) {
        Person person= new Person("Ahmet",37);

    }
    public record Person (String name, int age) {}
}
